{"name": "Сводный отчет по всем traceroute тестам", "status": "passed", "description": "Сводный отчет по всем traceroute тестам", "steps": [{"name": "Тестирование 192.168.43.2", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.43.2'", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "Traceroute к 192.168.43.2", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "Ошибка диаграммы", "source": "ff083cec-3c31-407c-99eb-01e3367abf14-attachment.attach"}, {"name": "Схема ожидаемого маршрута", "source": "aede8f73-2f27-447b-814f-b6070acd3991-attachment.txt", "type": "text/plain"}], "start": 1755749539708, "stop": 1755749539708}], "parameters": [{"name": "dst_ip", "value": "'192.168.43.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755749539708, "stop": 1755749539709}], "start": 1755749539708, "stop": 1755749539709}, {"name": "Тестирование 192.168.41.2", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.41.2'", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "Traceroute к 192.168.41.2", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "Ошибка диаграммы", "source": "c2d20cad-2b81-42ee-bae3-49fc363249c8-attachment.attach"}, {"name": "Схема ожидаемого маршрута", "source": "3e0b787e-0688-452e-b2c8-c1dc679b82be-attachment.txt", "type": "text/plain"}], "start": 1755749539710, "stop": 1755749539710}], "parameters": [{"name": "dst_ip", "value": "'192.168.41.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755749539709, "stop": 1755749539710}], "start": 1755749539709, "stop": 1755749539711}, {"name": "Тестирование 192.168.42.2", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.42.2'", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "steps": [{"name": "Traceroute к 192.168.42.2", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 85, in trace_route_to_ce\n    allure.attach(route_schema, name=\"Схема ожидаемого маршрута\", attachment_type=AttachmentType.TEXT)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 210, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_pytest/listener.py\", line 254, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/reporter.py\", line 165, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/logger.py\", line 48, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "Ошибка диаграммы", "source": "face7346-3794-46e0-b7b7-4b97859cf341-attachment.attach"}, {"name": "Схема ожидаемого маршрута", "source": "f49f8371-ecd5-4e68-9653-20da241a8fdb-attachment.txt", "type": "text/plain"}], "start": 1755749539711, "stop": 1755749539711}], "parameters": [{"name": "dst_ip", "value": "'192.168.42.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755749539711, "stop": 1755749539712}], "start": 1755749539711, "stop": 1755749539712}], "attachments": [{"name": "Сетевая топология", "source": "c280e3fa-ec1a-4c95-bb7f-0088fe812e97-attachment.png", "type": "image/png"}, {"name": "Описание топологии", "source": "ec729e61-1e40-4dab-bef0-57a256c8aefb-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9b37401f-e226-4f61-9f7b-d2c9b9461d55-attachment.txt", "type": "text/plain"}], "start": 1755749539685, "stop": 1755749539712, "uuid": "59eed975-c057-4e89-b307-2cf9e8cb56d5", "historyId": "e2d0d488f97cb8bdd959f464e4fba7ec", "testCaseId": "e2d0d488f97cb8bdd959f464e4fba7ec", "fullName": "test_traceroute#test_traceroute_summary", "labels": [{"name": "epic", "value": "Сетевые тесты"}, {"name": "feature", "value": "Сводный отчет"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "19500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}