{"name": "Сводный отчет по всем traceroute тестам", "status": "failed", "statusDetails": {"message": "AssertionError: Не все traceroute тесты прошли успешно\nassert False", "trace": "@allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Сводный отчет\")\n    @allure.title(\"Сводный отчет по всем traceroute тестам\")\n    def test_traceroute_summary():\n        \"\"\"Сводный отчет по всем traceroute тестам\"\"\"\n    \n        summary_results = {}\n    \n        for ce_ip in IP_DST:\n            with allure.step(f\"Тестирование {ce_ip}\"):\n                try:\n                    hops_info, reached = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n    \n                    # Считаем статистику\n                    correct_hops = sum(1 for hop in hops_info if hop['is_correct'] or hop['expected_ip'] == \"Unknown\")\n                    total_hops = len(hops_info)\n    \n                    summary_results[ce_ip] = {\n                        'success': reached and correct_hops == total_hops,\n                        'reached': reached,\n                        'correct_hops': correct_hops,\n                        'total_hops': total_hops,\n                        'path': [hop['actual_ip'] for hop in hops_info]\n                    }\n    \n                except Exception as e:\n                    summary_results[ce_ip] = {\n                        'success': False,\n                        'error': str(e)\n                    }\n    \n        # Создаем сводную таблицу для allure\n        summary_table = \"Цель | Успех | Достигнута | Правильные хопы | Всего хопов | Маршрут\\n\"\n        summary_table += \"-\" * 120 + \"\\n\"\n    \n        for ce_ip, result in summary_results.items():\n            if 'error' in result:\n                summary_table += f\"{ce_ip} | ❌ | - | - | - | Ошибка: {result['error']}\\n\"\n            else:\n                status = \"✅\" if result['success'] else \"❌\"\n                reached = \"✅\" if result['reached'] else \"❌\"\n                summary_table += f\"{ce_ip} | {status} | {reached} | {result['correct_hops']}/{result['total_hops']} | {result['total_hops']} | {' -> '.join(result['path'])}\\n\"\n    \n        allure.attach(summary_table, name=\"Сводная таблица результатов\")\n    \n        # Проверяем, что все тесты прошли успешно\n        all_success = all(result.get('success', False) for result in summary_results.values())\n>       assert all_success, \"Не все traceroute тесты прошли успешно\"\nE       AssertionError: Не все traceroute тесты прошли успешно\nE       assert False\n\ntest_traceroute.py:220: AssertionError"}, "description": "Сводный отчет по всем traceroute тестам", "steps": [{"name": "Тестирование 192.168.43.2", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.43.2'", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "steps": [{"name": "Traceroute к 192.168.43.2 через VLAN 4028", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "f76c53fe-4bcb-4ca0-8ba6-0f8e43511619-attachment.attach"}], "start": 1755684986355, "stop": 1755684986355}, {"name": "Хоп 1", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "start": 1755684986355, "stop": 1755684986356}], "parameters": [{"name": "dst_ip", "value": "'192.168.43.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755684986355, "stop": 1755684986356}], "start": 1755684986355, "stop": 1755684986356}, {"name": "Тестирование 192.168.41.2", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.41.2'", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "steps": [{"name": "Traceroute к 192.168.41.2 через VLAN 4028", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "e350a766-5f87-4f07-805d-d1957b979042-attachment.attach"}], "start": 1755684986356, "stop": 1755684986356}, {"name": "Хоп 1", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "start": 1755684986356, "stop": 1755684986357}], "parameters": [{"name": "dst_ip", "value": "'192.168.41.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755684986356, "stop": 1755684986357}], "start": 1755684986356, "stop": 1755684986357}, {"name": "Тестирование 192.168.42.2", "status": "passed", "steps": [{"name": "Выполнение traceroute к '192.168.42.2'", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "steps": [{"name": "Traceroute к 192.168.42.2 через VLAN 4028", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "55b6139b-7824-4aa5-8564-306945f28587-attachment.attach"}], "start": 1755684986357, "stop": 1755684986357}, {"name": "Хоп 1", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "start": 1755684986357, "stop": 1755684986358}], "parameters": [{"name": "dst_ip", "value": "'192.168.42.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755684986357, "stop": 1755684986358}], "start": 1755684986357, "stop": 1755684986358}], "attachments": [{"name": "Сводная таблица результатов", "source": "e926f874-fb53-4a34-9f73-4b41a4b8d30b-attachment.attach"}], "start": 1755684986355, "stop": 1755684986358, "uuid": "5e0fdc5d-8c09-473e-a5c8-3b0cee89d56f", "historyId": "e2d0d488f97cb8bdd959f464e4fba7ec", "testCaseId": "e2d0d488f97cb8bdd959f464e4fba7ec", "fullName": "test_traceroute#test_traceroute_summary", "labels": [{"name": "epic", "value": "Сетевые тесты"}, {"name": "feature", "value": "Сводный отчет"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "18149-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}