{"name": "Traceroute к 192.168.42.2", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted", "trace": "ce_ip = '192.168.42.2'\n\n    @allure.epic(\"Сетевые тесты\")\n    @allure.feature(\"Traceroute тестирование\")\n    @allure.title(\"Traceroute к CE устройствам\")\n    @allure.description(\"Тестирование маршрута до CE устройств через VLAN\")\n    @pytest.mark.parametrize(\"ce_ip\", IP_DST)\n    def test_traceroute_to_ce(ce_ip):\n        \"\"\"Тест traceroute с проверкой маршрута до CE устройств\"\"\"\n    \n        allure.dynamic.title(f\"Traceroute к {ce_ip}\")\n        allure.dynamic.description(f\"Проверка маршрута до устройства {ce_ip} через VLAN {VLAN_ID}\")\n    \n        with allure.step(\"Запуск traceroute\"):\n>           hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntest_traceroute.py:126: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_traceroute.py:48: in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\ntest_traceroute.py:29: in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../venv/lib/python3.12/site-packages/scapy/sendrecv.py:769: in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n../../venv/lib/python3.12/site-packages/scapy/sendrecv.py:756: in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n../../venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py:218: in __init__\n    self.ins = socket.socket(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <socket.socket fd=-1, family=0, type=0, proto=0>, family = <AddressFamily.AF_PACKET: 17>, type = <SocketKind.SOCK_RAW: 3>, proto = 768, fileno = None\n\n    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):\n        # For user code address family and type values are IntEnum members, but\n        # for the underlying _socket.socket they're just integers. The\n        # constructor of _socket.socket converts the given argument to an\n        # integer automatically.\n        if fileno is None:\n            if family == -1:\n                family = AF_INET\n            if type == -1:\n                type = SOCK_STREAM\n            if proto == -1:\n                proto = 0\n>       _socket.socket.__init__(self, family, type, proto, fileno)\nE       PermissionError: [Errno 1] Operation not permitted\n\n/usr/lib/python3.12/socket.py:233: PermissionError"}, "description": "Проверка маршрута до устройства 192.168.42.2 через VLAN 4028", "steps": [{"name": "Запуск traceroute", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 126, in test_traceroute_to_ce\n    hops_info, reached_destination = trace_route_to_ce(ce_ip, VLAN_ID, CE4_INTERFACE)\n                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "steps": [{"name": "Выполнение traceroute к '192.168.42.2'", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "steps": [{"name": "Traceroute к 192.168.42.2 через VLAN 4028", "status": "passed", "attachments": [{"name": "Ожидаемый маршрут", "source": "ae99087b-801b-43a2-8b3d-553eeba085cb-attachment.attach"}], "start": 1755684986326, "stop": 1755684986326}, {"name": "Хоп 1", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 1] Operation not permitted\n", "trace": "  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 48, in trace_route_to_ce\n    response_pkt = send_icmp_traceroute_via_vlan(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/task_3/tests/test_traceroute.py\", line 29, in send_icmp_traceroute_via_vlan\n    ans = srp1(pkt, iface=interface, timeout=TIMEOUT, verbose=0)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 769, in srp1\n    ans, _ = srp(*args, **kargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/sendrecv.py\", line 756, in srp\n    s = iface.l2socket()(promisc=promisc, iface=iface,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/veronika/eltex/venv/lib/python3.12/site-packages/scapy/arch/linux/__init__.py\", line 218, in __init__\n    self.ins = socket.socket(\n               ^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 233, in __init__\n    _socket.socket.__init__(self, family, type, proto, fileno)\n"}, "start": 1755684986326, "stop": 1755684986327}], "parameters": [{"name": "dst_ip", "value": "'192.168.42.2'"}, {"name": "vlan_id", "value": "4028"}, {"name": "interface", "value": "'enp3s0'"}], "start": 1755684986326, "stop": 1755684986327}], "start": 1755684986326, "stop": 1755684986327}], "parameters": [{"name": "ce_ip", "value": "'192.168.42.2'"}], "start": 1755684986326, "stop": 1755684986327, "uuid": "2e68f707-c1e7-45ca-89a6-70d3f8c0a1d1", "historyId": "6ebd27b58705b0f3c79aacfd0febe32a", "testCaseId": "430986e6801dc82aa72d8850714fa921", "fullName": "test_traceroute#test_traceroute_to_ce", "labels": [{"name": "feature", "value": "Traceroute тестирование"}, {"name": "epic", "value": "Сетевые тесты"}, {"name": "suite", "value": "test_traceroute"}, {"name": "host", "value": "bykova-veronika"}, {"name": "thread", "value": "18149-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_traceroute"}], "titlePath": ["test_traceroute.py"]}